# Generated by Django 5.1.4 on 2024-12-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('GR', 'GINGER'), ('PL', 'PLAIN'), ('ML', 'MASALA'), ('KL', 'KIWI'), ('EL', 'ELAICHI')], max_length=2),
        ),
    ]
