# Generated by Django 5.1.4 on 2024-12-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0002_alter_chaivarity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('EL', 'ELAICHI'), ('GR', 'GINGER'), ('ML', 'MASALA'), ('KL', 'KIWI'), ('PL', 'PLAIN')], max_length=2),
        ),
    ]
