# Generated by Django 5.1.4 on 2024-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0004_alter_chaivarity_type_chaicertificate_chaireview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('ML', 'MASALA'), ('EL', 'ELAICHI'), ('PL', 'PLAIN'), ('GR', 'GINGER'), ('KL', 'KIWI')], max_length=2),
        ),
    ]
